version: '3.8'

services:

  nodejs-api:
    build: .
    ports:
      - "8081"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123123
      - MYSQL_DATABASE=fi_projecta_development
    depends_on:
      - mysql
    # command: ["npx", "sequelize-cli", "db:migrate"]  # Run migration command after MySQL container is ready
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "123123"
      MYSQL_DATABASE: fi_projecta_development  # Specify the database name here
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: {}
